#!/usr/bin/env bash
#Bash script that displays Best School

i=0
while [[ $i -lt 10 ]]
do
    if [ $i = 3 ]; then
        echo "bad luck"
        i=$(( i + 1))
    elif [ $i = 7 ]; then
        echo "good luck "
        i=$(( i + 1))
    else
        echo "Best School"
        i=$(( i + 1))
    fi
done
